### PR TITLE
Python 2 and 3

### PR DESCRIPTION
**Pull request by kronos-cm**

### CODE REVIEW

**Comment by vesis84** [comment]
Hi, sorry for the long reaction time. I just noticed that there were pull requests recently. One quick question: Why was there the 'str_or_bytes' function necessary? Is it critical for supporting python3? Or is it just to make the code 'nicer'? Thanks, K.

**Comment by kronos-cm** [comment]
Yes, it is, because of the handling of strings in python3. I couldn't find a more "elegant" way of making it work for python3 while keeping it backward compatible.

**Comment by RicherMans** [comment]
In Python2, the following lines can be used to write a binary matrix to the output stream:
```python
import numpy as np
import sys
x = np.random.randn(10,10)
x.tofile(sys.stdout)
```
It works fine, but in Python3, there was a significant change in the writing structure ( and for some reason also for the numpy.tofile ). tofile now only accepts files, not stdout. 
A very simple fix to your code would be to replace every `m.tofile(fd,sep='')` with a 'fd.write(m.tobytes())'.

**Comment by vesis84** [comment]
Okay, I see... Have you also tried `x.tofile('/dev/stdout')`? This could be a 'hacky' work-around, but your solution is probably better :) Thanks, K.

**Comment by vesis84** [comment]
Hi, 
could you please take a look at the new branch: 
https://github.com/vesis84/kaldi-io-for-python/tree/py2py3

I incorporated your suggestion: 'tofile -> write', 
and also extended the compatibility for pythons 2 / 3.

Could both of you test it, please? (after that I'll merge it into 'master')
(to me it seemed a little slower, but not drastically)

Thank you, Karel.

**Comment by RicherMans** [comment]
Sorry for the later response, but your new branch py2py3 is only for python3 is that right?

**Comment by vesis84** [comment]
Aha, seems like I need to extend the unit test also for writing ;) Thanks! K.

**Comment by vesis84** [comment]
Hi,
I updated the branch 'py2py3'. Can you please test it again?
Now it should be compatible both with python2.x and python3.x 
(there is a new unit test for validating the I/O by 'read->write->read' of vectors and matrices).

Finally I decided to fix the type mismatch in python3 (the 'str' / 'byte' arrays),
by placing the '.encode(), .decode()' calls which is a no-op in python 2.x,
as it converts 'a string into same string'...

Thanks, Karel.

**Comment by RicherMans** [comment]
Small note: Please change the test data output directory
```python
with kaldi_io.open_or_fd('data_re-saved/ali.ark','wb') as f:
```

to:

```python
with kaldi_io.open_or_fd('data/ali.ark','wb') as f:
```

**Comment by vesis84** [comment]
Aha, I did not notice that the empty folder was not in the repo... This is easy to fix. Thanks for the helping, I'll merge it into the master now...
K.

**Comment by kronos-cm** [comment]
Hi Karel and Richel,

I have been running some tests and I couldn't notice a speed difference. I like the .encode() .decode() approach. I didn't know it was a no-op on python2. Thanks for this commit.
Best,
Angel

**Comment by vesis84** [comment]
Actually, the purpose of having '.encode()', '.decode()' methods is to change the encoding of strings (https://www.tutorialspoint.com/python/string_decode.htm) And if the encoding is kept to be the deafult, it does what we needed, it does nothing in python2...
Best, Karel

**Pull request closed without merging**
